/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.AccomodationData.SellAccomodation;
import Business.AccomodationData.SellAccomodationDirectory;
import Business.Enterprise.Enterprise;
import Business.HouseholdData.Household;
import Business.HouseholdData.HouseholdDirectory;
import Business.Logging.MyLogging;
import Business.Organization.AssisstantManagerOrganization;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccomodationAssisstantManagerWorkRequest;
import Business.WorkQueue.BookstoreAssisstantManagerWorkRequest;
import Business.WorkQueue.HouseholdAssisstantManagerWorkRequest;
import Business.WorkQueue.HouseholdWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.AssistantManagerRole.AssistantAccomodationManagerWorkAreaJPanel;

/**
 *
 * @author Jaynee
 */
public class SellHouseholdJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellAccomodationJPanel
     */
    HouseholdDirectory householdDir;
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount userAccount;
    Organization organization;
    
    public SellHouseholdJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount,Organization organization) {
        initComponents();
        this.householdDir = new HouseholdDirectory();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.organization=(StudentOrganization)organization;
        firstNameText.setText(userAccount.getUsername()+"");

          populateData();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quantityComboBox = new javax.swing.JComboBox();
        costText = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        createButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        sellHouseholdTable = new javax.swing.JTable();
        furnitureTypeText = new javax.swing.JTextField();
        viewSoldRequestsButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        chatButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Furniture type");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cost");

        quantityComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        costText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        createButton.setBackground(new java.awt.Color(102, 102, 102));
        createButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createButton.setText("SELL");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Username");

        firstNameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstNameText.setEnabled(false);

        sellHouseholdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Furniture Type", "Quantity", "Cost", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sellHouseholdTable);
        if (sellHouseholdTable.getColumnModel().getColumnCount() > 0) {
            sellHouseholdTable.getColumnModel().getColumn(0).setResizable(false);
            sellHouseholdTable.getColumnModel().getColumn(1).setResizable(false);
            sellHouseholdTable.getColumnModel().getColumn(2).setResizable(false);
            sellHouseholdTable.getColumnModel().getColumn(3).setResizable(false);
            sellHouseholdTable.getColumnModel().getColumn(4).setResizable(false);
            sellHouseholdTable.getColumnModel().getColumn(5).setResizable(false);
        }

        furnitureTypeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        viewSoldRequestsButton.setBackground(new java.awt.Color(102, 102, 102));
        viewSoldRequestsButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewSoldRequestsButton.setText("VIEW SOLD REQUESTS");
        viewSoldRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSoldRequestsButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(102, 102, 102));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        chatButton.setBackground(new java.awt.Color(102, 102, 102));
        chatButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chatButton.setText("CHAT");
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("HOUSEHOLD SELLING WORK AREA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46)
                                .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(furnitureTypeText, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(quantityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(costText)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(viewSoldRequestsButton)
                        .addGap(45, 45, 45)
                        .addComponent(chatButton)))
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(furnitureTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(quantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(viewSoldRequestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void populateData()
    {
        DefaultTableModel model = (DefaultTableModel) sellHouseholdTable.getModel();

        model.setRowCount(0);
//        for(Household household: householdDir.getHouseholdDataList())
//        {
//            Object row[] = new Object[10];
//            row[0]=household.getfName();
//            row[1]=household.getFurnitureType();
//            row[2]=household.getQuantity();
//            row[3]=household.getCost();
//            row[4] = household.getStatus();
//            String result = household.getResult();
//            row[5] = result == null ? "Waiting" : result;
//           ((DefaultTableModel) sellHouseholdTable.getModel()).addRow(row);
//        }
        
        
        for(HouseholdWorkRequest request : userAccount.getWorkQueue().getHouseholdWorkRequests()){
             Object[] row = new Object[6];
            row[0] = request.getfName();
            row[1] = request.getFurnitureType();
            row[2]=request.getQuantity();
            row[3]=request.getCost();
            row[4]=request.getStatus();
            String result = ((HouseholdAssisstantManagerWorkRequest) request).getTestResult();
            row[5] = result == null ? "Waiting" : result;
            model.addRow(row);
        }
    }
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        double cost =0.0;
        int  quantity = Integer.parseInt(quantityComboBox.getSelectedItem()+"");
                try{
                 cost =Double.parseDouble(costText.getText());
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Enter a valid number for the cost of furniture");
                    return;
                }
        
        String furnitureType =furnitureTypeText.getText();
        String fname= userAccount.getUsername();
        String status = "Pending";
        if(fname != null && fname.trim().length()>0 &&
                furnitureType != null && furnitureType.trim().length()>0)
        {
            householdDir.sellHouseholdInformation(furnitureType, cost, quantity, fname,status);

            populateData();

           //code to generate the  sell request of student in the queue of Manager

            HouseholdAssisstantManagerWorkRequest request = new HouseholdAssisstantManagerWorkRequest();

            request.setFurnitureType(furnitureType);
            request.setQuantity(quantity);
            request.setCost(cost);
            request.setfName(fname);
            request.setStatus("Pending");               


            Organization managerOrg = null;
            Organization studentOrg =null;
            Organization assistantManagerOrg=null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof ManagerOrganization){
                    managerOrg = organization;
                    break;
                }
            }
             for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof StudentOrganization){
                    studentOrg = organization;
                    break;
                }
            }
              for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof AssisstantManagerOrganization){
                    assistantManagerOrg = organization;
                    break;
                }
            }
            if (managerOrg!=null && studentOrg!=null && assistantManagerOrg!=null ){

                managerOrg.getWorkQueue().getHouseholdWorkRequests().add(request);
                //adding student request only to current student's account so that when other students log in they cant see current students request
                userAccount.getWorkQueue().getHouseholdWorkRequests().add(request);
                assistantManagerOrg.getWorkQueue().getHouseholdWorkRequests().add(request);
            }
                populateData();

            }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter all the value.");
        }
        
         MyLogging.log(Level.INFO, userAccount.getUsername()+ "  from  "  + enterprise +"   Enterprise posted a sell request on dashboard"); 
    }//GEN-LAST:event_createButtonActionPerformed

    private void viewSoldRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSoldRequestsButtonActionPerformed
         SoldHouseholdJPanel soldhouse = new SoldHouseholdJPanel(userProcessContainer,enterprise,userAccount,organization);
        userProcessContainer.add("SoldHouseholdJPanel", soldhouse);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewSoldRequestsButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        // TODO add your handling code here:

        System.out.println("2");
        TestChat_Client cc = new TestChat_Client();
        //chat_client cc = new chat_client();
        cc.setVisible(true);
        System.out.println("21");
    }//GEN-LAST:event_chatButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton chatButton;
    private javax.swing.JTextField costText;
    private javax.swing.JButton createButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JTextField furnitureTypeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox quantityComboBox;
    private javax.swing.JTable sellHouseholdTable;
    private javax.swing.JButton viewSoldRequestsButton;
    // End of variables declaration//GEN-END:variables
}
